package com.my.model;
// Generated Aug 20, 2013 11:22:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer attendance;
     private String description;
     private Integer fine;
     private Set<StudentHasEvent> studentHasEvents = new HashSet<StudentHasEvent>(0);

    public Event() {
    }

    public Event(String name, Integer attendance, String description, Integer fine, Set<StudentHasEvent> studentHasEvents) {
       this.name = name;
       this.attendance = attendance;
       this.description = description;
       this.fine = fine;
       this.studentHasEvents = studentHasEvents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAttendance() {
        return this.attendance;
    }
    
    public void setAttendance(Integer attendance) {
        this.attendance = attendance;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getFine() {
        return this.fine;
    }
    
    public void setFine(Integer fine) {
        this.fine = fine;
    }
    public Set<StudentHasEvent> getStudentHasEvents() {
        return this.studentHasEvents;
    }
    
    public void setStudentHasEvents(Set<StudentHasEvent> studentHasEvents) {
        this.studentHasEvents = studentHasEvents;
    }




}


