package com.my.model;
// Generated Aug 20, 2013 11:22:15 PM by Hibernate Tools 3.2.1.GA



/**
 * StudentHasEvent generated by hbm2java
 */
public class StudentHasEvent  implements java.io.Serializable {


     private Integer studentEventId;
     private Event event;
     private Student student;
     private Integer attendance;

    public StudentHasEvent() {
    }

    public StudentHasEvent(Event event, Student student, Integer attendance) {
       this.event = event;
       this.student = student;
       this.attendance = attendance;
    }
   
    public Integer getStudentEventId() {
        return this.studentEventId;
    }
    
    public void setStudentEventId(Integer studentEventId) {
        this.studentEventId = studentEventId;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Integer getAttendance() {
        return this.attendance;
    }
    
    public void setAttendance(Integer attendance) {
        this.attendance = attendance;
    }




}


