package com.my.model;
// Generated Aug 20, 2013 11:22:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int id;
     private String name;
     private Character status;
     private Character sex;
     private String course;
     private Integer year;
     private Set<StudentHasEvent> studentHasEvents = new HashSet<StudentHasEvent>(0);

    public Student() {
    }

	
    public Student(int id) {
        this.id = id;
    }
    public Student(int id, String name, Character status, Character sex, String course, Integer year, Set<StudentHasEvent> studentHasEvents) {
       this.id = id;
       this.name = name;
       this.status = status;
       this.sex = sex;
       this.course = course;
       this.year = year;
       this.studentHasEvents = studentHasEvents;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }
    public Character getSex() {
        return this.sex;
    }
    
    public void setSex(Character sex) {
        this.sex = sex;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Set<StudentHasEvent> getStudentHasEvents() {
        return this.studentHasEvents;
    }
    
    public void setStudentHasEvents(Set<StudentHasEvent> studentHasEvents) {
        this.studentHasEvents = studentHasEvents;
    }




}


