/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.my.ui;

import com.my.model.Event;
import com.my.model.Student;
import com.my.model.StudentHasEvent;
import com.my.service.ServiceClass;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author User
 */
public class AttendancePanel extends javax.swing.JPanel {

    /**
     * Creates new form AttendancePanel
     */
    Student student = new Student();
    Event event = new  Event();
    
    public AttendancePanel() {
        initComponents();
        createEventPanel.setVisible(false);
        groupRadioButtons();
    }

    private void groupRadioButtons(){
        ButtonGroup chooseStudentSex = new ButtonGroup();
            chooseStudentSex.add(rbChooseStudentSexMale);
            chooseStudentSex.add(rbChooseStudentSexFemale);
        ButtonGroup chooseStudentStatus = new ButtonGroup();
            chooseStudentStatus.add(rbChooseStudentStatusOld);
            chooseStudentStatus.add(rbChooseStudentStatusNew);
            chooseStudentStatus.add(rbChooseStudentStatusReturning);
            chooseStudentStatus.add(rbChooseStudentStatusTransferee);
//        rbChooseStudentSexMale.setSelected(true);
//        rbChooseStudentStatusOld.setSelected(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        attendDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        lblAttendEvent = new javax.swing.JLabel();
        attendFilterPanel = new javax.swing.JPanel();
        tfAttendId = new javax.swing.JTextField();
        rbAttendSexMale = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        tfAttendCourse = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rbAttendStatusOld = new javax.swing.JRadioButton();
        rbAttendStatusTransferee = new javax.swing.JRadioButton();
        tfAttendYear = new javax.swing.JTextField();
        rbAttendSexFemale = new javax.swing.JRadioButton();
        rbAttendStatusNew = new javax.swing.JRadioButton();
        rbAttendStatusReturning = new javax.swing.JRadioButton();
        cbAttendName = new javax.swing.JCheckBox();
        cbAttendId = new javax.swing.JCheckBox();
        tfAttendName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        attendList = ObservableCollections.observableList(new LinkedList<StudentHasEvent>());
        chooseStudentList = ObservableCollections.observableList(new LinkedList<Student>());
        chooseStudentDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChooseStudent = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ChooseStudentFilterPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rbChooseStudentStatusReturning = new javax.swing.JRadioButton();
        tfChooseStudentCourse = new javax.swing.JTextField();
        rbChooseStudentStatusOld = new javax.swing.JRadioButton();
        rbChooseStudentSexFemale = new javax.swing.JRadioButton();
        cbChooseStudentId = new javax.swing.JCheckBox();
        cbChooseStudentName = new javax.swing.JCheckBox();
        tfChooseStudentName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfChooseStudentId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rbChooseStudentStatusTransferee = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        rbChooseStudentStatusNew = new javax.swing.JRadioButton();
        tfChooseStudentYear = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rbChooseStudentSexMale = new javax.swing.JRadioButton();
        chooseEventDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChooseEvent = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfChooseEventId = new javax.swing.JTextField();
        tfChooseEventName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfChooseEventAttendance = new javax.swing.JTextField();
        cbChooseEventId = new javax.swing.JCheckBox();
        cbChooseEventName = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        createEventPanel = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfNewEventDescription = new javax.swing.JTextArea();
        tfNewEventAttendance = new javax.swing.JTextField();
        tfNewEventName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        chooseEventList = ObservableCollections.observableList(new LinkedList<Event>());
        decimalCellRenderer1 = new com.my.service.DecimalCellRenderer();
        studentAttendances = ObservableCollections.observableList(new LinkedList<StudentHasEvent>());
        btnAttend = new javax.swing.JButton();
        btnChooseStudent = new javax.swing.JButton();
        lblStudentName = new javax.swing.JLabel();
        btnChooseEvent = new javax.swing.JButton();
        lblEventName = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        lblFines = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        attendDialog.setMinimumSize(new java.awt.Dimension(500, 500));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, attendList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${studentEventId}"));
        columnBinding.setColumnName("Student Event Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${student.name}"));
        columnBinding.setColumnName("Student");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${attendance}"));
        columnBinding.setColumnName("Attendance");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(decimalCellRenderer1);

        jButton8.setText("Filter");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setText("Done");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        lblAttendEvent.setText("EVENT NAME");

        tfAttendId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAttendIdKeyPressed(evt);
            }
        });

        rbAttendSexMale.setText("Male");
        rbAttendSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAttendSexMaleActionPerformed(evt);
            }
        });

        jLabel21.setText("Status:");

        tfAttendCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAttendCourseKeyPressed(evt);
            }
        });

        jLabel18.setText("Course:");

        jLabel19.setText("Year:");

        jLabel20.setText("Sex:");

        rbAttendStatusOld.setText("Old");

        rbAttendStatusTransferee.setText("Transferee");

        tfAttendYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAttendYearKeyPressed(evt);
            }
        });

        rbAttendSexFemale.setText("Female");
        rbAttendSexFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAttendSexFemaleActionPerformed(evt);
            }
        });

        rbAttendStatusNew.setText("New");

        rbAttendStatusReturning.setText("Returning");

        cbAttendName.setText("Exact");

        cbAttendId.setText("Exact");

        tfAttendName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAttendNameKeyPressed(evt);
            }
        });

        jLabel7.setText("Name:");

        jLabel6.setText("ID:");

        javax.swing.GroupLayout attendFilterPanelLayout = new javax.swing.GroupLayout(attendFilterPanel);
        attendFilterPanel.setLayout(attendFilterPanelLayout);
        attendFilterPanelLayout.setHorizontalGroup(
            attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attendFilterPanelLayout.createSequentialGroup()
                        .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(attendFilterPanelLayout.createSequentialGroup()
                                .addComponent(rbAttendSexMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAttendSexFemale)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAttendYear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfAttendCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(attendFilterPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(attendFilterPanelLayout.createSequentialGroup()
                                .addComponent(tfAttendName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAttendName))
                            .addGroup(attendFilterPanelLayout.createSequentialGroup()
                                .addComponent(tfAttendId, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbAttendId))))
                    .addGroup(attendFilterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(3, 3, 3)
                        .addComponent(rbAttendStatusOld)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbAttendStatusReturning)
                        .addGap(3, 3, 3)
                        .addComponent(rbAttendStatusTransferee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbAttendStatusNew)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        attendFilterPanelLayout.setVerticalGroup(
            attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendFilterPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAttendId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAttendId)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAttendName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAttendName)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfAttendCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(rbAttendSexMale)
                    .addComponent(rbAttendSexFemale)
                    .addComponent(jLabel19)
                    .addComponent(tfAttendYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attendFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAttendStatusOld)
                    .addComponent(jLabel21)
                    .addComponent(rbAttendStatusReturning)
                    .addComponent(rbAttendStatusTransferee)
                    .addComponent(rbAttendStatusNew))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout attendDialogLayout = new javax.swing.GroupLayout(attendDialog.getContentPane());
        attendDialog.getContentPane().setLayout(attendDialogLayout);
        attendDialogLayout.setHorizontalGroup(
            attendDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendDialogLayout.createSequentialGroup()
                .addGroup(attendDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attendDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(attendDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attendFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(attendDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendDialogLayout.createSequentialGroup()
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendDialogLayout.createSequentialGroup()
                            .addComponent(lblAttendEvent)
                            .addGap(203, 203, 203)))))
        );
        attendDialogLayout.setVerticalGroup(
            attendDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAttendEvent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(attendFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        chooseStudentDialog.setMinimumSize(new java.awt.Dimension(550, 600));
        chooseStudentDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chooseStudentDialogKeyPressed(evt);
            }
        });

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, chooseStudentList, tblChooseStudent);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${course}"));
        columnBinding.setColumnName("Course");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sex}"));
        columnBinding.setColumnName("Sex");
        columnBinding.setColumnClass(Character.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${status}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(Character.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${year}"));
        columnBinding.setColumnName("Year");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tblChooseStudent);

        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("FILTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("Sex:");

        rbChooseStudentStatusReturning.setText("Returning");

        tfChooseStudentCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChooseStudentCourseKeyPressed(evt);
            }
        });

        rbChooseStudentStatusOld.setText("Old");

        rbChooseStudentSexFemale.setText("Female");
        rbChooseStudentSexFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbChooseStudentSexFemaleActionPerformed(evt);
            }
        });

        cbChooseStudentId.setText("Exact");

        cbChooseStudentName.setText("Exact");

        tfChooseStudentName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChooseStudentNameKeyPressed(evt);
            }
        });

        jLabel1.setText("ID:");

        tfChooseStudentId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChooseStudentIdKeyPressed(evt);
            }
        });

        jLabel2.setText("Name:");

        jLabel14.setText("Course:");

        rbChooseStudentStatusTransferee.setText("Transferee");

        jLabel16.setText("Year:");

        rbChooseStudentStatusNew.setText("New");

        tfChooseStudentYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChooseStudentYearKeyPressed(evt);
            }
        });

        jLabel17.setText("Status:");

        rbChooseStudentSexMale.setText("Male");
        rbChooseStudentSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbChooseStudentSexMaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChooseStudentFilterPanelLayout = new javax.swing.GroupLayout(ChooseStudentFilterPanel);
        ChooseStudentFilterPanel.setLayout(ChooseStudentFilterPanelLayout);
        ChooseStudentFilterPanelLayout.setHorizontalGroup(
            ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChooseStudentFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChooseStudentFilterPanelLayout.createSequentialGroup()
                        .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ChooseStudentFilterPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(rbChooseStudentStatusOld)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbChooseStudentStatusReturning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbChooseStudentStatusTransferee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbChooseStudentStatusNew))
                            .addComponent(jLabel17))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ChooseStudentFilterPanelLayout.createSequentialGroup()
                        .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ChooseStudentFilterPanelLayout.createSequentialGroup()
                                .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfChooseStudentId)
                                    .addComponent(tfChooseStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbChooseStudentId)
                                    .addComponent(cbChooseStudentName)))
                            .addComponent(tfChooseStudentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ChooseStudentFilterPanelLayout.createSequentialGroup()
                                .addComponent(rbChooseStudentSexMale)
                                .addGap(18, 18, 18)
                                .addComponent(rbChooseStudentSexFemale)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(tfChooseStudentYear)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ChooseStudentFilterPanelLayout.setVerticalGroup(
            ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChooseStudentFilterPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfChooseStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChooseStudentId))
                .addGap(18, 18, 18)
                .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfChooseStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChooseStudentName))
                .addGap(18, 18, 18)
                .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfChooseStudentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbChooseStudentSexFemale)
                    .addComponent(jLabel15)
                    .addComponent(rbChooseStudentSexMale)
                    .addComponent(jLabel16)
                    .addComponent(tfChooseStudentYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ChooseStudentFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(rbChooseStudentStatusOld)
                    .addComponent(rbChooseStudentStatusReturning)
                    .addComponent(rbChooseStudentStatusTransferee)
                    .addComponent(rbChooseStudentStatusNew))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chooseStudentDialogLayout = new javax.swing.GroupLayout(chooseStudentDialog.getContentPane());
        chooseStudentDialog.getContentPane().setLayout(chooseStudentDialogLayout);
        chooseStudentDialogLayout.setHorizontalGroup(
            chooseStudentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseStudentDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(44, 44, 44))
            .addGroup(chooseStudentDialogLayout.createSequentialGroup()
                .addGroup(chooseStudentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chooseStudentDialogLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(ChooseStudentFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chooseStudentDialogLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        chooseStudentDialogLayout.setVerticalGroup(
            chooseStudentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseStudentDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChooseStudentFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        chooseEventDialog.setMinimumSize(new java.awt.Dimension(450, 450));
        chooseEventDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chooseEventDialogKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chooseEventDialogKeyReleased(evt);
            }
        });

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, chooseEventList, tblChooseEvent);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${description}"));
        columnBinding.setColumnName("Description");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${attendance}"));
        columnBinding.setColumnName("Attendance");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(tblChooseEvent);

        jButton6.setText("Done");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        jLabel4.setText("Name:");

        tfChooseEventId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChooseEventIdKeyPressed(evt);
            }
        });

        tfChooseEventName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChooseEventNameKeyPressed(evt);
            }
        });

        jLabel5.setText("Attendance:");

        tfChooseEventAttendance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChooseEventAttendanceKeyPressed(evt);
            }
        });

        cbChooseEventId.setText("Exact");

        cbChooseEventName.setText("Exact");

        jButton7.setText("Filter");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("New Event");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Done");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        tfNewEventDescription.setColumns(20);
        tfNewEventDescription.setRows(5);
        jScrollPane4.setViewportView(tfNewEventDescription);

        jLabel8.setText("New Event");

        jLabel9.setText("Name:");

        jLabel10.setText(" Attendance:");

        jLabel11.setText("Event Description:");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createEventPanelLayout = new javax.swing.GroupLayout(createEventPanel);
        createEventPanel.setLayout(createEventPanelLayout);
        createEventPanelLayout.setHorizontalGroup(
            createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEventPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createEventPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel8))
                    .addGroup(createEventPanelLayout.createSequentialGroup()
                        .addGroup(createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createEventPanelLayout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfNewEventAttendance)
                                .addComponent(jScrollPane4)
                                .addComponent(tfNewEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
        );
        createEventPanelLayout.setVerticalGroup(
            createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfNewEventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNewEventAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout chooseEventDialogLayout = new javax.swing.GroupLayout(chooseEventDialog.getContentPane());
        chooseEventDialog.getContentPane().setLayout(chooseEventDialogLayout);
        chooseEventDialogLayout.setHorizontalGroup(
            chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseEventDialogLayout.createSequentialGroup()
                .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(chooseEventDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(chooseEventDialogLayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(chooseEventDialogLayout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(chooseEventDialogLayout.createSequentialGroup()
                                    .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfChooseEventAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                        .addComponent(tfChooseEventId)
                                        .addComponent(tfChooseEventName))
                                    .addGap(18, 18, 18)
                                    .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbChooseEventId)
                                        .addComponent(cbChooseEventName)))))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseEventDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createEventPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        chooseEventDialogLayout.setVerticalGroup(
            chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseEventDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfChooseEventId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChooseEventId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfChooseEventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChooseEventName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfChooseEventAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chooseEventDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createEventPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        decimalCellRenderer1.setText("decimalCellRenderer1");

        setPreferredSize(new java.awt.Dimension(1330, 691));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        btnAttend.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAttend.setText("Attend");
        btnAttend.setEnabled(false);
        btnAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendActionPerformed(evt);
            }
        });

        btnChooseStudent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnChooseStudent.setText("Choose Student");
        btnChooseStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseStudentActionPerformed(evt);
            }
        });

        lblStudentName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStudentName.setText("Student Name");

        btnChooseEvent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnChooseEvent.setText("Choose Event");
        btnChooseEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseEventActionPerformed(evt);
            }
        });

        lblEventName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEventName.setText("Event Name");

        jTable4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable4.setRowHeight(32);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, studentAttendances, jTable4);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${studentEventId}"));
        columnBinding.setColumnName("Student Event Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${event.name}"));
        columnBinding.setColumnName("Event");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${attendance}"));
        columnBinding.setColumnName("Attendance");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane5.setViewportView(jTable4);
        jTable4.getColumnModel().getColumn(0).setResizable(false);
        jTable4.getColumnModel().getColumn(1).setResizable(false);
        jTable4.getColumnModel().getColumn(2).setResizable(false);

        lblFines.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFines.setText("FINES");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("STUDENT NAME:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("EVENT NAME:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChooseStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChooseEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAttend, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 760, Short.MAX_VALUE))
            .addComponent(jScrollPane5)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEventName)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStudentName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFines)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentName)
                    .addComponent(lblFines)
                    .addComponent(jLabel12))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblEventName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseEvent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChooseStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(btnAttend, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendActionPerformed
        lblAttendEvent.setText(event.getName());
        attendList.clear();
        attendList.addAll(new ServiceClass().getAllStudentHasEvents(event));
        attendDialog.setModal(true);
        attendDialog.setLocationRelativeTo(null);
        attendDialog.setVisible(true);
        lblAttendEvent.setText(event.getName());
        
    }//GEN-LAST:event_btnAttendActionPerformed

    private void btnChooseStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseStudentActionPerformed
        chooseStudentList.clear();
        chooseStudentList.addAll(new ServiceClass().get100Students());
        tblChooseStudent.setRowSelectionInterval(0, 0);
        chooseStudentDialog.setModal(true);
        chooseStudentDialog.setLocationRelativeTo(null);
        chooseStudentDialog.setVisible(true);
        
    }//GEN-LAST:event_btnChooseStudentActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        student = chooseStudentList.get(tblChooseStudent.getSelectedRow());
        lblStudentName.setText(student.getName());
        chooseStudentDialog.setVisible(false);
        updateStudentAttendance();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnChooseEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseEventActionPerformed
        chooseEventList.clear();
        chooseEventList.addAll(new ServiceClass().getAllEvents());
        
        if (!chooseEventList.isEmpty())
            tblChooseEvent.setRowSelectionInterval(0, 0);
        
        chooseEventDialog.setModal(true);
        chooseEventDialog.setLocationRelativeTo(null);
        chooseEventDialog.setVisible(true);
    }//GEN-LAST:event_btnChooseEventActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        event = chooseEventList.get(tblChooseEvent.getSelectedRow());
        lblEventName.setText(event.getName());
        chooseEventDialog.setVisible(false);
        btnAttend.setEnabled(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      filterChooseStudent();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tfChooseStudentIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChooseStudentIdKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            filterChooseStudent();
    }//GEN-LAST:event_tfChooseStudentIdKeyPressed

    private void tfChooseStudentNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChooseStudentNameKeyPressed
          if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            filterChooseStudent();
    }//GEN-LAST:event_tfChooseStudentNameKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void chooseStudentDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chooseStudentDialogKeyPressed

    }//GEN-LAST:event_chooseStudentDialogKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        filterChooseEvent();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tfChooseEventIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChooseEventIdKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            filterChooseEvent();
    }//GEN-LAST:event_tfChooseEventIdKeyPressed

    private void tfChooseEventNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChooseEventNameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
                    filterChooseEvent();
    }//GEN-LAST:event_tfChooseEventNameKeyPressed

    private void tfChooseEventAttendanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChooseEventAttendanceKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            filterChooseEvent();
    }//GEN-LAST:event_tfChooseEventAttendanceKeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            filterAttend();
                    
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tfAttendIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAttendIdKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            filterAttend();
    }//GEN-LAST:event_tfAttendIdKeyPressed

    private void tfAttendNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAttendNameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            filterAttend();
    }//GEN-LAST:event_tfAttendNameKeyPressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Event event = new Event();
            event.setName(tfNewEventName.getText());
            event.setAttendance(Integer.parseInt(tfNewEventAttendance.getText()));
            event.setDescription(tfNewEventDescription.getText());
        new ServiceClass().addEvent(event);
        JOptionPane.showMessageDialog(this, "Event Successfully Added!", "Success!", JOptionPane.INFORMATION_MESSAGE);
        new ServiceClass().addAllStudentsAttendance(event);
        chooseEventDialog.setSize(450,450);
        createEventPanel.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      createEventPanel.setVisible(true);
      chooseEventDialog.setSize(450,700);
      chooseEventDialog.setLocation(450, 10);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int[] selectedRows = jTable1.getSelectedRows();
        List<StudentHasEvent> list = new ArrayList<StudentHasEvent>();
        
        for(Integer i :selectedRows){
            list.add(attendList.get(i));
        }
        
        new ServiceClass().updateBundleStudentHasEvents(list);
        
        updateStudentAttendance();
        JOptionPane.showMessageDialog(this, "Attendances Saved!", "Success!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        selectAllCell(jTable1,jTable1.getSelectedRow(),jTable1.getSelectedColumn());
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selectAllCell(jTable1,jTable1.getSelectedRow(),jTable1.getSelectedColumn());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        int maximumAttendance = event.getAttendance();
        int value = (Integer)jTable1.getModel().getValueAt(jTable1.getSelectedRow(),2);
        if(value>maximumAttendance)
            jTable1.getModel().setValueAt(maximumAttendance,jTable1.getSelectedRow(), 2);
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
      
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost

    }//GEN-LAST:event_jTable1FocusLost

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained

    }//GEN-LAST:event_jTable1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        createEventPanel.setVisible(false);
        chooseEventDialog.setSize(450,450);
        chooseEventDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chooseEventDialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chooseEventDialogKeyPressed

    }//GEN-LAST:event_chooseEventDialogKeyPressed

    private void chooseEventDialogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chooseEventDialogKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseEventDialogKeyReleased

    private void rbChooseStudentSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbChooseStudentSexMaleActionPerformed

    }//GEN-LAST:event_rbChooseStudentSexMaleActionPerformed

    private void rbChooseStudentSexFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbChooseStudentSexFemaleActionPerformed

    }//GEN-LAST:event_rbChooseStudentSexFemaleActionPerformed

    private void tfChooseStudentCourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChooseStudentCourseKeyPressed
          if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            filterChooseStudent();
    }//GEN-LAST:event_tfChooseStudentCourseKeyPressed

    private void tfChooseStudentYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChooseStudentYearKeyPressed
          if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            filterChooseStudent();
    }//GEN-LAST:event_tfChooseStudentYearKeyPressed

    private void rbAttendSexFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAttendSexFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAttendSexFemaleActionPerformed

    private void tfAttendYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAttendYearKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAttendYearKeyPressed

    private void tfAttendCourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAttendCourseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAttendCourseKeyPressed

    private void rbAttendSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAttendSexMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAttendSexMaleActionPerformed
    
    private void filterAttend(){
        Map param = new HashMap();
            param.put("id",tfAttendId.getText());
            param.put("name",tfAttendName.getText());
            param.put("idExact",cbAttendId.isSelected());
            param.put("nameExact",cbAttendId.isSelected());
            param.put("event",event);
            param.put("course",tfAttendCourse.getText());
            param.put("male",rbAttendSexMale.isSelected());
            param.put("female",rbAttendSexFemale.isSelected());
            param.put("year",tfAttendYear.getText());
            param.put("old",rbAttendStatusOld.isSelected());
            param.put("returning",rbAttendStatusReturning.isSelected());
            param.put("transferee",rbAttendStatusTransferee.isSelected());
            param.put("new",rbAttendStatusNew.isSelected());
        attendList.clear();
        attendList.addAll(new ServiceClass().getAttendFiltered(param));
    }
    
    private void filterChooseEvent(){
        Map param = new HashMap();
            param.put("id", tfChooseEventId.getText());
            param.put("name",tfChooseEventName.getText());
            param.put("attendance",tfChooseEventAttendance.getText());
            param.put("idExact",cbChooseEventId.isSelected());
            param.put("nameExact",cbChooseEventName.isSelected());
        chooseEventList.clear();
        chooseEventList.addAll(new ServiceClass().getChooseEventFiltered(param));
        if(!chooseEventList.isEmpty())
            tblChooseEvent.setRowSelectionInterval(0, 0);
    }
    
    private void filterChooseStudent(){
        Map param = new HashMap();
            param.put("id",tfChooseStudentId.getText());
            param.put("name",tfChooseStudentName.getText());
            param.put("idExact",cbChooseStudentId.isSelected());
            param.put("nameExact",cbChooseStudentName.isSelected());
            param.put("course",tfChooseStudentCourse.getText());
            param.put("male",rbChooseStudentSexMale.isSelected());
            param.put("female",rbChooseStudentSexFemale.isSelected());
            param.put("year",tfChooseStudentYear.getText());
            param.put("old",rbChooseStudentStatusOld.isSelected());
            param.put("returning",rbChooseStudentStatusReturning.isSelected());
            param.put("transferee",rbChooseStudentStatusTransferee.isSelected());
            param.put("new",rbChooseStudentStatusNew.isSelected());
            
            
        chooseStudentList.clear();
        chooseStudentList.addAll(new ServiceClass().getChooseStudentFiltered(param)); 
        
        if(!chooseStudentList.isEmpty())
            tblChooseStudent.setRowSelectionInterval(0, 0);
    }
    
    private void updateStudentAttendance(){
        studentAttendances.clear();
        studentAttendances.addAll(new ServiceClass().getStudentAttendances(student));
         computeFines();
    }
    
    private void computeFines(){
        int computedFee = 0;
        Event event = new Event();
        for(StudentHasEvent she: studentAttendances){
            event = she.getEvent();
            computedFee = computedFee + (event.getAttendance() - she.getAttendance())*event.getFine();
        }
        lblFines.setText("Fines:" + computedFee);
    }
    
    private void selectAllCell(JTable jTable,int row, int column){

        if(row >= 0 && column >=0){
            jTable.editCellAt(row,column);
            DefaultCellEditor cellEditor = (DefaultCellEditor)jTable.getCellEditor(row,column);
            JTextField field1 = (JTextField)cellEditor.getComponent();
            field1.selectAll();
            field1.requestFocus();
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChooseStudentFilterPanel;
    private javax.swing.JDialog attendDialog;
    private javax.swing.JPanel attendFilterPanel;
    private java.util.List<StudentHasEvent> attendList;
    private javax.swing.JButton btnAttend;
    private javax.swing.JButton btnChooseEvent;
    private javax.swing.JButton btnChooseStudent;
    private javax.swing.JCheckBox cbAttendId;
    private javax.swing.JCheckBox cbAttendName;
    private javax.swing.JCheckBox cbChooseEventId;
    private javax.swing.JCheckBox cbChooseEventName;
    private javax.swing.JCheckBox cbChooseStudentId;
    private javax.swing.JCheckBox cbChooseStudentName;
    private javax.swing.JDialog chooseEventDialog;
    private java.util.List<Event> chooseEventList;
    private javax.swing.JDialog chooseStudentDialog;
    private java.util.List<Student> chooseStudentList;
    private javax.swing.JPanel createEventPanel;
    private com.my.service.DecimalCellRenderer decimalCellRenderer1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblAttendEvent;
    private javax.swing.JLabel lblEventName;
    private javax.swing.JLabel lblFines;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JRadioButton rbAttendSexFemale;
    private javax.swing.JRadioButton rbAttendSexMale;
    private javax.swing.JRadioButton rbAttendStatusNew;
    private javax.swing.JRadioButton rbAttendStatusOld;
    private javax.swing.JRadioButton rbAttendStatusReturning;
    private javax.swing.JRadioButton rbAttendStatusTransferee;
    private javax.swing.JRadioButton rbChooseStudentSexFemale;
    private javax.swing.JRadioButton rbChooseStudentSexMale;
    private javax.swing.JRadioButton rbChooseStudentStatusNew;
    private javax.swing.JRadioButton rbChooseStudentStatusOld;
    private javax.swing.JRadioButton rbChooseStudentStatusReturning;
    private javax.swing.JRadioButton rbChooseStudentStatusTransferee;
    private java.util.List<StudentHasEvent> studentAttendances;
    private javax.swing.JTable tblChooseEvent;
    private javax.swing.JTable tblChooseStudent;
    private javax.swing.JTextField tfAttendCourse;
    private javax.swing.JTextField tfAttendId;
    private javax.swing.JTextField tfAttendName;
    private javax.swing.JTextField tfAttendYear;
    private javax.swing.JTextField tfChooseEventAttendance;
    private javax.swing.JTextField tfChooseEventId;
    private javax.swing.JTextField tfChooseEventName;
    private javax.swing.JTextField tfChooseStudentCourse;
    private javax.swing.JTextField tfChooseStudentId;
    private javax.swing.JTextField tfChooseStudentName;
    private javax.swing.JTextField tfChooseStudentYear;
    private javax.swing.JTextField tfNewEventAttendance;
    private javax.swing.JTextArea tfNewEventDescription;
    private javax.swing.JTextField tfNewEventName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
